# Generated by Django 3.1.6 on 2021-02-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rnum',
            field=models.CharField(max_length=25),
        ),
    ]
